name: Rust

on:
  push:
    branches: [ "master" ]
    tags: [ "v*" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y pkg-config libudev-dev cloud-guest-utils xfsprogs btrfs-progs
      - name: Install Rust
        run: |
          rustup update stable
          rustup default stable
          rustup component add rustfmt clippy
      - name: Check formatting
        run: cargo fmt --all -- --check
      - name: Run clippy
        run: cargo clippy -- -D warnings

  test:
    name: Test
    needs: check
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust: [stable, beta]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-${{ matrix.rust }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y pkg-config libudev-dev cloud-guest-utils xfsprogs btrfs-progs
      - name: Install Rust
        run: |
          rustup update ${{ matrix.rust }}
          rustup default ${{ matrix.rust }}
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose

  build:
    name: Build
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y pkg-config libudev-dev
      - name: Install Rust
        run: |
          rustup update stable
          rustup default stable
      - name: Build release
        run: cargo build --release --verbose
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: hot-resize
          path: target/release/hot-resize

  release:
    name: Release
    if: startsWith(github.ref, 'refs/tags/v')
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: hot-resize
          path: .
      - name: Make executable
        run: chmod +x hot-resize
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: hot-resize
          draft: false
          prerelease: false
